---
title: "Auto-correlation"
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
library("forecast")
library("tibbletime")
```

## Generate data

```{r}
set.seed(42)

n <- 512

# no trend
trendless <- as.integer(rnorm(n, 3000, 200))
trend <- ma(trendless, order = 4, centre = T)
plot(as.ts(trendless), col = 'blue')
lines(trend, col = 'red')

# trend
trendfull <- cumsum(as.integer(rnorm(n, 2, 10)))
trendfull <- tail(head(trendfull, 300), 150)
trend <- ma(trendfull, order = 8, centre = T)
plot(as.ts(trendfull), col = 'blue')
lines(trend, col = 'red')
```

## Auto-correlation (built in)

```{r}
acf(trendless, lag.max = 1, type = c("correlation"), plot = TRUE, na.action = na.fail)
acf(trendfull, lag.max = 1, type = c("correlation"), plot = TRUE, na.action = na.fail)
```

## Rolling auto-correlation (trendfull)

```{r}
window_size <- 10

#acf(trendfull, plot = TRUE, lag.max = window_size - 1)

acf_lag <- function(elt, lag) {
  acf(elt, plot = FALSE, lag.max = lag)$acf[1 + lag]
}

acf_lag_1 <- function(elt) {
  acf_lag(elt, 1)
}

acf_lag_2 <- function(elt) {
  acf_lag(elt, 2)
}

acf_window <- rollify(acf_lag_1, window = window_size)

trendfull_df <- as.data.frame(trendfull)

trendfull_df <- trendfull_df %>%
  mutate(ac = acf_window(trendfull)) %>%
  mutate(num = seq_along(trendfull)) %>%
  mutate(trend = ma(trendfull, order = window_size, centre = T) / 500) %>%
  mutate(
    trend = replace_na(trend, 0),
    ac = replace_na(ac, 0)
  )

trendfull_df

ggplot() +
  geom_line(data = trendfull_df, aes(x = num, y = ac), size = 0.5, color = "#0000cc") +
  geom_line(data = trendfull_df, aes(x = num, y = trend), size = 0.5, color = "#cc0000")
  
```

## Rolling auto-correlation (trendless)

```{r}
#acf(trendless, lag.max = 1)

trendless_df <- as.data.frame(trendless)

trendless_df <- trendless_df %>%
  mutate(ac = acf_window(trendless)) %>%
  mutate(num = seq_along(trendless)) %>%
  mutate(trend = ma(trendless, order = window_size, centre = T) / 5000) %>%
  mutate(
    trend = replace_na(trend, 0),
    ac = replace_na(ac, 0)
  )

trendless_df

ggplot() +
  geom_line(data = trendless_df, aes(x = num, y = ac), size = 0.5, color = "#0000cc") +
  geom_line(data = trendless_df, aes(x = num, y = trend), size = 0.5, color = "#cc0000")
  
```

## Generate data with trend

```{r}
set.seed(42)
window_size <- 50

trendless2_pos <- as.integer(rnorm(n / 2, 3000, 200))
trendless2_neg <- as.integer(-rnorm(n / 2, 3000, 200))

trendless2 <- c(trendless2_pos, trendless2_neg)
trendless2 <- sample(trendless2)

trendfull2 <- cumsum(as.integer(rnorm(n / 10, 100, 700)))
trendfull2 <- tail(head(trendfull2, 50), 50)
plot(trendfull2)
acf(trendfull2, lag.max = 1)

chunks <- split(trendless2, ceiling(seq_along(trendless2) / 256))

trendless2 <- c(unlist(chunks[1]), trendfull2, unlist(chunks[2]))

trendless2_df <- data.frame(trendless2)

trendless2_df <- trendless2_df %>%
  mutate(num = seq_along(trendless2)) %>%
  mutate(sum = cumsum(trendless2)) %>%
  mutate(trend = ma(sum, order = window_size, centre = T)) %>%
  mutate(ac = acf_window(trendless2)) %>%
  mutate(
    trend = replace_na(trend, 0),
    sum = replace_na(sum, 0),
    ac = replace_na(ac, 0)
  )
  

trendless2_df
  
ggplot() +
  geom_line(data = trendless2_df, aes(x = num, y = sum), size = 0.5, color = "#0000cc") +
  geom_line(data = trendless2_df, aes(x = num, y = trend), size = 0.5, color = "#cc0000")
  
ggplot() +
  geom_line(data = trendless2_df, aes(x = num, y = ac), size = 0.5, color = "#0000cc")
  
```



